### ISSUE TITLE
Create interactive mode

### ISSUE THREAD

**Issue by sharpchi** [hugoacfs/upgroodle#1]
Especially for testing purposes, it would be good to have an interactive mode which stops at critical points to ask if it's ok to continue. This would be good for identifying any issues that might fly by unnoticed when reams of logging flies by on the screen.
Suggested option -i

**Comment by hugoacfs** [comment]
d91a99f82c2448a21cc59d595785f5e9e9cb9ed7
Added interactive mode to get_moodle function as a trial. Will implement to rest of the code if it works as intended.

**Comment by hugoacfs** [comment]
658bf94bc031741e6e418878904d3db6bf4598d9
Introducing colour to interactive mode. Will add interactive mode to more functions.

**Comment by hugoacfs** [comment]
64a9a2e3989c1595ac70a62d353189544c0e381e
New tag v0.2 introduces interactive mode.
